### ISSUE TITLE
get the code

### ISSUE THREAD

**Issue by lordmen99** [tuhinpal/bingchat-api#3]
hi where is get this code from this :

 So, you should have beta access. After deployment login to that bing account and open developer console. Then paste the code (replace your serverUrl).

i have been get beta bing chat

**Comment by tuhinpal** [comment]
const cookie = document.cookie;
const serverUrl = "http://localhost:8080";

fetch(`${serverUrl}/set-cookie`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({ cookie }),
})
  .then((res) => res.json())
  .then((res) => console.log(res))
  .catch((err) => console.log(err));

**Comment by lordmen99** [comment]
i try create conversation get this error :
{
    "message": "Error creating conversation"
}

**Comment by tuhinpal** [comment]
![image](https://user-images.githubusercontent.com/51857187/221760435-db11c010-4aba-48c2-9bd3-89ab8186b583.png)

Or create a `cookie.txt` in root dir and insert your bing cookie (run `document.cookie`)

**Comment by tuhinpal** [comment]
I hope your issue is resolved. Fell free to reopen if it is not.
