### ISSUE TITLE
How can I get the content of bing chat response using iOS shortcuts?

### ISSUE THREAD

**Issue by bigplayer-ai** [tuhinpal/bingchat-api#4]
Hey,
I am trying to make bing chat chatbot on my iPhone.
How can I get the content of bing chat response using iOS shortcuts?

**Comment by tuhinpal** [comment]
Referred you to [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource).

**Comment by bigplayer-ai** [comment]
I want something local on my iPhone only.

**Comment by tuhinpal** [comment]
I have no Idea, I don't have an iphone for experiment.
